version: '3.5'
services:
  php:
    image: bagrat92/laravel-kubernetes:latest
    restart: always
    ports:
      - 8000:80
    environment:
      - APP_KEY="base64:nCWIUVUUsA5Ggcyc6FRrXDOXIN1wCUJBx2zV/co1W/E="
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_PORT=3306
      - DB_HOST=mysql
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=local_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
